{% set name = "swmm-toolkit" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
    sha256: 83e8e9dccbac785aa4868643cdfc3972ff7ffe06f04fdfa6f603b82f5c643e72

build:
  script:
    - set NO_STABLE_ABI=true  # [win]
    - export NO_STABLE_ABI=true  # [unix]
    - export SKBUILD_CMAKE_ARGS="-GUnix Makefiles"  # [unix]
    - export SKBUILD_CMAKE_ARGS="-GUnix Ninja"  # [win]
    - export CFLAGS="${CFLAGS} -D_FORTIFY_SOURCE=2"  # [osx]
    - export CXXFLAGS="${CXXFLAGS} -D_FORTIFY_SOURCE=2"  # [osx]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

  number: 1
  skip: true  # [py<38]
  missing_dso_whitelist:   # [win]
    - "*/swmm5.dll"  # [win]
    - "*/swmm-output.dll"  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - git-lfs
    - cmake >=3.21
    - swig >=4.4.0
    - make  # [unix]
    - ninja  # [win]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - vcomp14  # [win]
  host:
    - python
    - setuptools >=42
    - scikit-build-core >=0.4.3
    - pip
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - vcomp14  # [win]
  run:
    - python
    - aenum >=3.1.11

test:
  imports:
    - swmm.toolkit.solver
    - swmm.toolkit.output
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/OpenWaterAnalytics/swmm-python
  summary: OWA SWMM Python Toolkit
  license: CC0-1.0
  license_file:
    - LICENSE.md
    - swmm-solver/LICENSE

extra:
  recipe-maintainers:
    - karosc
    - cheginit
